In [1]:
import pandas as pd

In [7]:
bars_seen_train= pd.read_parquet('C:/Users/chris/Desktop/datathon_2026/ETH_Datathon_2026/data/bars_seen_train.parquet')

In [8]:
bars_seen_train.head()

   bar_ix  session  open    high     low   close
0       0        0   1.0  1.0029  0.9986  0.9999
1       0        1   1.0  1.0024  0.9980  1.0011
2       0        2   1.0  1.0005  0.9952  0.9957
3       0        3   1.0  1.0008  0.9986  1.0008
4       0        4   1.0  1.0031  0.9996  1.0009

In [14]:
(bars_seen_train.isna().sum()/len(bars_seen_train)).sort_values(ascending=False)

bar_ix     0.0
session    0.0
open       0.0
high       0.0
low        0.0
close      0.0
dtype: float64

In [10]:
bars_seen_train.shape

(50000, 6)

In [11]:
bars_unseen_train= pd.read_parquet('C:/Users/chris/Desktop/datathon_2026/ETH_Datathon_2026/data/bars_unseen_train.parquet')

In [12]:
bars_unseen_train

         bar_ix  session    open    high     low   close
1050000      50        0  1.0318  1.0375  1.0318  1.0367
1050001      50        1  1.0283  1.0297  1.0261  1.0282
1050002      50        2  1.0204  1.0217  1.0179  1.0202
1050003      50        3  1.0117  1.0129  1.0112  1.0126
1050004      50        4  1.0281  1.0296  1.0263  1.0274
...         ...      ...     ...     ...     ...     ...
2079995      99      995  0.9833  0.9837  0.9811  0.9812
2079996      99      996  1.0684  1.0685  1.0638  1.0661
2079997      99      997  1.0058  1.0060  1.0019  1.0028
2079998      99      998  1.0014  1.0033  1.0001  1.0028
2079999      99      999  1.0324  1.0330  1.0308  1.0325

[50000 rows x 6 columns]

In [16]:
headlines_seen_train= pd.read_parquet('C:/Users/chris/Desktop/datathon_2026/ETH_Datathon_2026/data/headlines_seen_train.parquet')

In [21]:
headlines_seen_train['headline']

0        Relvos Biosciences opens new office in Southea...
1        Orevex Renewables secures $500M contract with ...
2        Relvos Biosciences names new head of precision...
3        Calvis Sciences secures $650M contract with a ...
4        Yorvov Pharmaceuticals secures $180M contract ...
                               ...
17355    Yorval Partners begins scheduled maintenance o...
17356    Yorval Partners announces breakthrough in auto...
17357    Krevan Investments withdraws from Scandinavia ...
17358    Wrelal Financial secures $800M contract with a...
17359    Zelvix Therapeutics recalls products in digita...
Name: headline, Length: 9740, dtype: object

In [22]:
headlines_seen_train

       session                                           headline  bar_ix
0            0  Relvos Biosciences opens new office in Southea...       6
1            0  Orevex Renewables secures $500M contract with ...      12
2            0  Relvos Biosciences names new head of precision...      14
3            0  Calvis Sciences secures $650M contract with a ...      20
4            0  Yorvov Pharmaceuticals secures $180M contract ...      22
...        ...                                                ...     ...
17355      999  Yorval Partners begins scheduled maintenance o...      33
17356      999  Yorval Partners announces breakthrough in auto...      33
17357      999  Krevan Investments withdraws from Scandinavia ...      41
17358      999  Wrelal Financial secures $800M contract with a...      45
17359      999  Zelvix Therapeutics recalls products in digita...      45

[9740 rows x 3 columns]